driveparts/candystore/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from goods import urls
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from goods.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('goods.urls')),
    path('users/',include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),


]+debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = "Авто товары"

driveparts/goods/urls.py
from django.urls import path
from goods import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path("", views.GoodsHome.as_view(), name='home'),
    path("card-page/<slug:gd_slug>/",views.CardPage.as_view(),name='card-page'),
    path("category/<slug:cat_slug>",views.GoodsCategory.as_view(), name='cat'),
    path('tag/<slug:tag_slug>/', views.GoodsTags.as_view(), name='tag'),
    path('add-prod/', views.AddProd.as_view(), name='add-prod'),
    path('about/', views.about, name='about'),
    path('delete-prod/<slug:slug>', views.DeletePage.as_view(), name='delete-prod'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
]

driveparts/users/urls.py
from django.urls import path
from users  import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', views.UserPasswordChangeDone.as_view(), name='password_change_done'),

    path('password-reset/',views.UserResetView.as_view(), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile')
]

driveparts/goods/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from transliterate import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model

#Create my own manager
class Main_Manager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Goods.Status.IN_STOCK)


# Create your models here.
class Goods(models.Model):
    class Status(models.IntegerChoices):
        OUT_OF_STOKE = 0, 'Не в наличии'
        IN_STOCK = 1, 'В наличии'

    name = models.CharField(max_length=255, verbose_name='Имя')
    slug = AutoSlugField(populate_from = 'name')
    photo = models.ImageField(upload_to="images/%Y/%m/%d/",null=True,blank=True, verbose_name='Фото')
    desc = models.TextField(blank=True)
    cats = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, related_name='goods')
    tags = models.ManyToManyField('Tags', blank=True, related_name='gtags')
    status = models.BooleanField(Status,default=Status.OUT_OF_STOKE)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='goods', null=True, default=None )
    

    objects = models.Manager()
    manager = Main_Manager() 


    def slugify_function(self,content):
        return slugify(content)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Авто товары"
        verbose_name_plural = "Авто товары"
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]

    def get_absolute_url(self):
        return reverse('card-page', kwargs={'gd_slug': self.slug})

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Имя')
    slug = AutoSlugField(populate_from = 'name')
    
    class Meta:
        verbose_name = "Категории"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name
    
    def slugify_function(self,content):
        return slugify(content)
    
    def get_absolute_url(self):
        return reverse('cat', kwargs={'cat_slug': self.slug})
    
class Tags(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = AutoSlugField(populate_from = 'tag')

    def __str__(self):
        return self.tag
    
    def slugify_function(self,content):
        return slugify(content)
    
    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})
    
class UploadFiles(models.Model):
    file = models.FileField(upload_to='upload_model')

driveparts/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True,verbose_name='Фотография')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')

driveparts/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from datetime import date


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput())
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    
    class Meta:
        model = get_user_model()
class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1','password2', ]
        labels = {
                'first_name':'Имя',
                'last_name':'Фамилия',
                }
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует')
        return email
    
class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True,label='Логин')
    email = forms.EmailField(disabled=True)
    this_year = date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5))))

    class Meta:
        model = get_user_model()
        fields = ['photo','username', 'email','date_birth', 'first_name', 'last_name']
        labels = {
                'first_name':'Имя',
                'last_name':'Фамилия',
                }
    
class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старый пароль",
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "autofocus": True}
        ))
    new_password1 = forms.CharField(label='Новый пароль:',widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Подтверждение пароля:',widget=forms.PasswordInput())

driveparts/users/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.views import LoginView, PasswordChangeView,PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView

from django.views.generic import CreateView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    # def get_success_url(self):
    #     return reverse('home')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

class ProfileUser(LoginRequiredMixin, UpdateView):
    # model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    def get_success_url(self):
        return reverse_lazy('users:profile')
    
    def get_object(self, queryset = ...):
        return self.request.user
    
class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change.html"

class UserPasswordChangeDone(PasswordChangeDoneView):
    template_name = "users/password_change_done.html"

class UserResetView(PasswordResetView):
    template_name='users/password_reset_form.html'
    email_template_name = "users/password_reset_email.html",
    success_url = reverse_lazy("users:password_reset_done")

class UserPasswordResetConfirm(PasswordResetConfirmView):
    template_name='users/password_reset_confirm.html'
    success_url = reverse_lazy("users:password_reset_complete")

driveparts/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}

<h1>Авторизация</h1>

<form method="POST"  novalidate >
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {{ form.as_p }}
    <p><button type="submit">Войти</button></p>
</form>
<a href="{% url 'users:password_reset' %}">Забыли пароль?</a>

<p>
    <a  href="{% provider_login_url 'github' %}">
      <img src="/media/social-auth/github.png" alt="github" width="50">
    </a>
</p>
<p> {{ test }}</p>
{% endblock content %}

driveparts/users/templates/users/password_change.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ title }}</h1>

<form method="POST"  novalidate >
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock content %}

driveparts/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}

<h1>Смена пароля прошла успешно</h1>
<p>Для авторизации нужно перейти по <a href="{% url 'users:login' %}">ссылке</a></p>

{% endblock content %}

driveparts/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}

<h1>Восстановление пароля прошло успешно</h1>
<p>Для авторизации нужно перейти по <a href="{% url 'users:login' %}">ссылке</a></p>

{% endblock content %}

driveparts/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}

<h1>Новый пароль</h1>

<form method="POST"  novalidate >
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock content %}

driveparts/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block content %}

<h1>Инструкции сброшены на указанный E-mail</h1>

{% endblock content %}

driveparts/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

driveparts/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block content %}

<h1>Восстановление пароля</h1>

<form method="POST"  novalidate >
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock content %}

driveparts/users/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}

<h1>Профиль</h1>


<form method="POST" enctype="multipart/form-data" novalidate >
    {% csrf_token %}
    {% if user.photo %}
        <p><img src="{{ user.photo.url }}" width="100" alt="#"></p>
    {% endif %}
    {{ form.as_p }}
    <p><button type="submit">Сохранить</button></p>
</form>

{% if not perms.users.social_auth %}
<hr>
<p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
    
{% endif %}
{% if perms.goods.change_goods %}
    
<p> {{ test }}</p>
{% endif %}
{% endblock content %}

driveparts/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}

<h1>Регистрация</h1>

<form method="POST"  novalidate >
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {{ form.as_p }}
    <p><button type="submit">Регистрация</button></p>
</form>

<p> {{ test }}</p>
{% endblock content %}

driveparts/users/templates/users/register_done.html
{% extends 'base.html' %}
{% block content %}

<h1>Регистрация прошла успешно</h1>
<p>Для авторизации нужно перейти по <a href="{% url 'users:login' %}">ссылке</a></p>

{% endblock content %}