driveparts/candystore/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from goods import urls
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from goods.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('goods.urls')),
    path('users/',include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),


]+debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = "Авто товары"

driveparts/goods/urls.py
from django.urls import path
from goods import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path("", views.GoodsHome.as_view(), name='home'),
    path("card-page/<slug:gd_slug>/",views.CardPage.as_view(),name='card-page'),
    path("category/<slug:cat_slug>",views.GoodsCategory.as_view(), name='cat'),
    path('tag/<slug:tag_slug>/', views.GoodsTags.as_view(), name='tag'),
    path('add-prod/', views.AddProd.as_view(), name='add-prod'),
    path('about/', views.about, name='about'),
    path('delete-prod/<slug:slug>', views.DeletePage.as_view(), name='delete-prod'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
]

driveparts/users/urls.py
from django.urls import path
from users  import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', views.UserPasswordChangeDone.as_view(), name='password_change_done'),

    path('password-reset/',views.UserResetView.as_view(), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile')
]

driveparts/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load goods_tags %}
<!-- % load cache %} -->


<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->

<!-- perms Разрешения для таблицы -->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link type="text/css"  rel="stylesheet" href="{% static 'goods/css/style.css' %}">
        
    </head>
    <body>
        <header>
            
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'add-prod' %}">Добавить товар</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">Action</a></li>
                          <li><a class="dropdown-item" href="#">Another action</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}" tabindex="-1" >О сайте</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}" tabindex="-1" >Обратная связь</a>
                      </li>
                    </ul>
                    <form class="d-flex">
                      {% if user.is_authenticated %}
                         <h2><a href="{% url 'users:profile' %}">{{ user.username }}</a></h2>
                         <button class="btn btn-outline-success" type="submit"><a class="nav-link" href="{% url 'users:logout' %}">Выйти</a></button>
                      {% else %}
                         <button class="btn btn-outline-success" type="submit"><a class="nav-link" href="{% url 'users:login' %}">Войти</a></button>
                         
                         <button class="btn btn-outline-success" type="submit"><a class="nav-link" href="{% url 'users:register' %}">Регистрация</a></button>
                      {% endif %}
                    </form>
                  </div>
                </div>
              </nav>
        </header>
        <section>
          <!-- % cache 30 sidebar %} -->
        <div class="container-fluid m-4">
          <div class="row">
             <div class="col-lg-1">
              <h5>Категории</h5>
               <ul class="left-side">
                 {% show_categories %}
                 
               </ul>
               {% show_tags %}
             </div>
             <div class="col-lg-8 col-md-12">
               {% block content %}
                   
               {% endblock content %}

              
             </div>
          </div>
       </div>
       <!-- % end %} -->
        </section>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <footer>
            
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>